<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PIO-L-4110" failures="0" tests="13" name="com.nucleus.qa.testcases.CoreSystemTesting2" time="828.788" errors="1" timestamp="2024-12-23T16:34:51 IST" skipped="0">
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase8" time="64.739"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase10" time="90.687"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase12" time="53.576"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase11" time="104.642"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase7" time="56.041"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase6" time="102.371"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="Exit" time="1.606">
    <error message="Cannot invoke &quot;org.apache.poi.hssf.usermodel.HSSFSheet.createRow(int)&quot; because &quot;sheet&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.hssf.usermodel.HSSFSheet.createRow(int)" because "sheet" is null
at com.nucleus.qa.testcases.WriteCode.Write(WriteCode.java:30)
at com.nucleus.qa.testcases.CoreSystemTesting2.Exit(CoreSystemTesting2.java:3228)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:386)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.nucleus.qa.testcases.Runner.main(Runner.java:223)
]]>
    </error>
  </testcase> <!-- Exit -->
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase9" time="74.780"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase4" time="62.842"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase1" time="56.396"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase2" time="34.678"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase5" time="69.588"/>
  <testcase classname="com.nucleus.qa.testcases.CoreSystemTesting2" name="TestCase3" time="56.842"/>
</testsuite> <!-- com.nucleus.qa.testcases.CoreSystemTesting2 -->
